micronaut:
  application:
    name: projetoPixRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10
logger:
  levels:
    io.micronaut.transaction: DEBUG
